name: CICD

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Extract release tag
        run: echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      
      - name: chmod gradle
        run: chmod +x ./gradlew
       
      - name: build
        run: ./gradlew build --no-daemon
        
      - name: check build
        run: ls ./build/libs
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
          
      - name: docker build
        run: |
          echo "Deploying version $RELEASE_TAG"
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cidc:$RELEASE_TAG .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cidc:$RELEASE_TAG .
      - name: docker images check
        run: docker images
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docer push
        run: | 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cidc:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cidc:latest
